image: lazka/gitlab-gtk:v1

stages:
  - build

before_script:
  - mkdir -p _ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/_ccache

cache:
  paths:
    - _ccache/
    - subprojects/gdk-pixbuf/
    - subprojects/glib/
    - subprojects/graphene/
    - subprojects/libepoxy/
    - subprojects/pango/

build:
  stage: build
  script:
   - bash -x ./.gitlab-ci/test-docker.sh
