image: fedora:27

stages:
  - build

before_script:
  - dnf install -y gcc meson gettext itstool redhat-rpm-config git
                   glib2-devel
                   gobject-introspection-devel
                   json-glib-devel cups-devel colord-devel
                   libxkbcommon-devel
                   libXrender-devel libXcomposite-devel libXcursor-devel
                   libXfixes-devel libXcursor-devel libXi-devel
                   libXdamage-devel libXinerama-devel libXrandr-devel
                   libepoxy-devel at-spi2-atk-devel avahi-gobject-devel
                   cairo-devel cairo-gobject-devel atk-devel
                   wayland-devel wayland-protocols-devel
                   mesa-libEGL-devel mesa-libwayland-egl-devel
                   vulkan-devel

build:
  stage: build
  script:
    - meson -Denable-x11-backend=true -Denable-wayland-backend=true -Denable-broadway-backend=true -Denable-vulkan=yes _build_full
    - cd _build_full
    - ninja
